# coding: utf-8

"""
    Agent Platform

    This is a specification for openapi using  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agentPlatform@grs.uh.cu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import lib_agent
from lib_agent.models.addr import Addr  # noqa: E501
from lib_agent.rest import ApiException


class TestAddr(unittest.TestCase):
    """Addr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddr(self):
        """Test Addr"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lib_agent.models.addr.Addr()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
