# coding: utf-8

"""
    Agent Platform

    This is a specification for openapi using  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: agentPlatform@grs.uh.cu
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from lib_agent.configuration import Configuration


class TestCase(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'input': 'str',
        'output': 'str'
    }

    attribute_map = {
        'input': 'Input',
        'output': 'Output'
    }

    def __init__(self, input=None, output=None, local_vars_configuration=None):  # noqa: E501
        """TestCase - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._input = None
        self._output = None
        self.discriminator = None

        self.input = input
        self.output = output

    @property
    def input(self):
        """Gets the input of this TestCase.  # noqa: E501


        :return: The input of this TestCase.  # noqa: E501
        :rtype: str
        """
        return self._input

    @input.setter
    def input(self, input):
        """Sets the input of this TestCase.


        :param input: The input of this TestCase.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and input is None:  # noqa: E501
            raise ValueError("Invalid value for `input`, must not be `None`")  # noqa: E501

        self._input = input

    @property
    def output(self):
        """Gets the output of this TestCase.  # noqa: E501


        :return: The output of this TestCase.  # noqa: E501
        :rtype: str
        """
        return self._output

    @output.setter
    def output(self, output):
        """Sets the output of this TestCase.


        :param output: The output of this TestCase.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and output is None:  # noqa: E501
            raise ValueError("Invalid value for `output`, must not be `None`")  # noqa: E501

        self._output = output

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestCase):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TestCase):
            return True

        return self.to_dict() != other.to_dict()
